export interface Recipe {
  id: string;
  name: string;
  description: string;
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'pre_workout' | 'post_workout' | 'snack';
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: string;
  ingredients: string[];
  steps: string[];
  goals: string[];
  dietaryTags: string[];
  tips?: string;
}

export const RECIPES: Recipe[] = [
  // ===== BREAKFAST =====
  {
    id: 'bf-001',
    name: 'Protein-Packed Scrambled Eggs',
    description: 'Fluffy eggs with spinach and a side of avocado for sustained morning energy.',
    mealType: 'breakfast',
    calories: 320,
    protein: 22,
    carbs: 8,
    fat: 24,
    prepTime: '10 min',
    ingredients: ['3 large eggs', '1 cup spinach', '1/2 avocado', '1 tsp olive oil', 'Salt and pepper'],
    steps: ['Heat olive oil in a non-stick pan over medium heat.', 'Whisk eggs with salt and pepper.', 'Add spinach to the pan and wilt for 30 seconds.', 'Pour in eggs and scramble until set.', 'Serve with sliced avocado on the side.'],
    goals: ['lose', 'fat_burn', 'build_muscle', 'maintain'],
    dietaryTags: ['vegetarian', 'gluten_free', 'keto', 'paleo'],
    tips: 'Add a pinch of red pepper flakes for a metabolism boost.',
  },
  {
    id: 'bf-002',
    name: 'Greek Yogurt Power Bowl',
    description: 'Creamy Greek yogurt topped with berries, nuts, and a drizzle of honey.',
    mealType: 'breakfast',
    calories: 280,
    protein: 18,
    carbs: 32,
    fat: 9,
    prepTime: '5 min',
    ingredients: ['1 cup Greek yogurt (plain)', '1/2 cup blueberries', '2 tbsp almonds (chopped)', '1 tsp honey', '1 tbsp chia seeds'],
    steps: ['Spoon Greek yogurt into a bowl.', 'Top with blueberries and chia seeds.', 'Sprinkle chopped almonds.', 'Drizzle honey on top.'],
    goals: ['lose', 'maintain', 'gain', 'build_muscle'],
    dietaryTags: ['vegetarian', 'gluten_free'],
    tips: 'Use dairy-free yogurt for a vegan version.',
  },
  {
    id: 'bf-003',
    name: 'Overnight Oats with Banana & Peanut Butter',
    description: 'Make-ahead oats packed with carbs and protein for a filling breakfast.',
    mealType: 'breakfast',
    calories: 380,
    protein: 12,
    carbs: 55,
    fat: 13,
    prepTime: '5 min + overnight',
    ingredients: ['1/2 cup rolled oats', '1 banana (sliced)', '1 tbsp peanut butter', '1 cup almond milk', '1 tbsp chia seeds'],
    steps: ['Combine oats, chia seeds, and almond milk in a jar.', 'Stir well and refrigerate overnight.', 'In the morning, top with banana slices and peanut butter.'],
    goals: ['gain', 'build_muscle', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
    tips: 'Great for meal prep — make 3 jars at once.',
  },
  {
    id: 'bf-004',
    name: 'Avocado Toast with Poached Egg',
    description: 'Creamy avocado on whole grain toast topped with a perfectly poached egg.',
    mealType: 'breakfast',
    calories: 340,
    protein: 14,
    carbs: 30,
    fat: 18,
    prepTime: '12 min',
    ingredients: ['1 slice whole wheat bread', '1/2 avocado', '1 egg', 'Lemon juice', 'Red pepper flakes', 'Salt'],
    steps: ['Toast the bread until golden.', 'Mash avocado with lemon juice and salt.', 'Bring water to a gentle simmer and poach the egg for 3 minutes.', 'Spread avocado on toast, top with poached egg and red pepper flakes.'],
    goals: ['maintain', 'build_muscle'],
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'bf-005',
    name: 'Tofu Veggie Scramble',
    description: 'High-protein vegan scramble with turmeric, bell peppers, and kale.',
    mealType: 'breakfast',
    calories: 250,
    protein: 18,
    carbs: 12,
    fat: 15,
    prepTime: '15 min',
    ingredients: ['200g firm tofu', '1/2 bell pepper (diced)', '1 cup kale (chopped)', '1/2 tsp turmeric', '1 tbsp nutritional yeast', '1 tsp olive oil'],
    steps: ['Heat olive oil in a pan over medium heat.', 'Crumble tofu into the pan.', 'Add turmeric and nutritional yeast, stir well.', 'Add bell pepper and cook 3 minutes.', 'Add kale and cook until wilted.'],
    goals: ['lose', 'fat_burn', 'build_muscle', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'Add a dash of soy sauce for extra flavor.',
  },
  {
    id: 'bf-006',
    name: 'Cottage Cheese Pancakes',
    description: 'Fluffy high-protein pancakes that keep you full for hours.',
    mealType: 'breakfast',
    calories: 360,
    protein: 28,
    carbs: 28,
    fat: 14,
    prepTime: '20 min',
    ingredients: ['1 cup cottage cheese', '2 eggs', '1/2 cup oat flour', '1 tsp baking powder', '1 tsp vanilla extract', '1 tbsp honey'],
    steps: ['Blend cottage cheese, eggs, vanilla, and honey until smooth.', 'Mix in oat flour and baking powder.', 'Cook on a greased pan over medium heat, 2-3 minutes per side.', 'Serve with fresh berries.'],
    goals: ['build_muscle', 'gain', 'maintain'],
    dietaryTags: ['vegetarian', 'gluten_free'],
  },

  // ===== LUNCH =====
  {
    id: 'ln-001',
    name: 'Grilled Chicken Caesar Salad',
    description: 'Classic Caesar with lean grilled chicken and a light yogurt dressing.',
    mealType: 'lunch',
    calories: 420,
    protein: 38,
    carbs: 18,
    fat: 22,
    prepTime: '20 min',
    ingredients: ['150g chicken breast', '4 cups romaine lettuce', '2 tbsp Greek yogurt', '1 tbsp lemon juice', '1 tbsp parmesan', '1/4 cup whole wheat croutons', '1 tsp olive oil'],
    steps: ['Season chicken with salt and pepper, grill 6-8 minutes per side.', 'Chop romaine and place in a large bowl.', 'Whisk yogurt, lemon juice, and parmesan for dressing.', 'Slice chicken and add to salad with croutons.', 'Toss with dressing and serve.'],
    goals: ['lose', 'fat_burn', 'build_muscle', 'maintain'],
    dietaryTags: ['gluten_free'],
    tips: 'Skip croutons for a lower-carb version.',
  },
  {
    id: 'ln-002',
    name: 'Quinoa Buddha Bowl',
    description: 'Colorful bowl with quinoa, roasted veggies, chickpeas, and tahini dressing.',
    mealType: 'lunch',
    calories: 450,
    protein: 18,
    carbs: 62,
    fat: 16,
    prepTime: '30 min',
    ingredients: ['1 cup cooked quinoa', '1/2 cup chickpeas (roasted)', '1 cup roasted sweet potato', '1 cup kale', '1/4 avocado', '2 tbsp tahini', '1 tbsp lemon juice'],
    steps: ['Roast sweet potato cubes at 400°F for 20 minutes.', 'Roast chickpeas with spices for 15 minutes.', 'Massage kale with a little olive oil.', 'Arrange quinoa, veggies, chickpeas, and avocado in a bowl.', 'Drizzle with tahini mixed with lemon juice.'],
    goals: ['maintain', 'gain', 'build_muscle'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
  },
  {
    id: 'ln-003',
    name: 'Tuna Salad Stuffed Avocado',
    description: 'Low-carb lunch with tuna mixed in a creamy avocado boat.',
    mealType: 'lunch',
    calories: 310,
    protein: 28,
    carbs: 11,
    fat: 19,
    prepTime: '10 min',
    ingredients: ['1 can tuna (drained)', '1 avocado', '1 tbsp Greek yogurt', '1 tsp Dijon mustard', '1 celery stalk (diced)', 'Lemon juice', 'Salt and pepper'],
    steps: ['Cut avocado in half and remove pit.', 'Mix tuna, yogurt, mustard, celery, and lemon juice.', 'Season with salt and pepper.', 'Spoon tuna mixture into avocado halves.'],
    goals: ['lose', 'fat_burn', 'maintain'],
    dietaryTags: ['gluten_free', 'keto', 'paleo'],
  },
  {
    id: 'ln-004',
    name: 'Lentil Soup with Spinach',
    description: 'Hearty plant-based soup rich in protein and fiber.',
    mealType: 'lunch',
    calories: 280,
    protein: 16,
    carbs: 42,
    fat: 5,
    prepTime: '35 min',
    ingredients: ['1 cup dry lentils', '1 onion (diced)', '2 carrots (diced)', '2 garlic cloves', '4 cups vegetable broth', '2 cups fresh spinach', '1 tsp cumin', '1 tsp olive oil'],
    steps: ['Heat olive oil and sauté onion, carrots, and garlic.', 'Add cumin and stir for 30 seconds.', 'Add lentils and broth, bring to a boil.', 'Simmer for 25 minutes until lentils are tender.', 'Stir in spinach until wilted.'],
    goals: ['lose', 'fat_burn', 'maintain', 'gain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'Batch cook and freeze for easy lunches.',
  },
  {
    id: 'ln-005',
    name: 'Chicken & Brown Rice Power Bowl',
    description: 'Balanced bowl with grilled chicken, brown rice, and steamed broccoli.',
    mealType: 'lunch',
    calories: 480,
    protein: 40,
    carbs: 48,
    fat: 12,
    prepTime: '25 min',
    ingredients: ['150g chicken breast', '1 cup cooked brown rice', '1 cup broccoli', '1 tbsp soy sauce', '1 tsp sesame oil', '1 tsp olive oil', 'Sesame seeds'],
    steps: ['Cook brown rice according to package directions.', 'Grill chicken until cooked through, then slice.', 'Steam broccoli for 4 minutes.', 'Arrange rice, chicken, and broccoli in a bowl.', 'Drizzle with soy sauce and sesame oil, top with sesame seeds.'],
    goals: ['build_muscle', 'gain', 'maintain'],
    dietaryTags: ['gluten_free'],
  },

  // ===== DINNER =====
  {
    id: 'dn-001',
    name: 'Baked Salmon with Asparagus',
    description: 'Omega-3 rich salmon with tender asparagus — simple and elegant.',
    mealType: 'dinner',
    calories: 380,
    protein: 32,
    carbs: 10,
    fat: 22,
    prepTime: '25 min',
    ingredients: ['180g salmon fillet', '1 bunch asparagus', '1 tbsp olive oil', '1 lemon', '2 garlic cloves (minced)', 'Salt and pepper', 'Fresh dill'],
    steps: ['Preheat oven to 400°F.', 'Place salmon and asparagus on a baking sheet.', 'Drizzle with olive oil, minced garlic, salt, and pepper.', 'Bake for 15-18 minutes.', 'Squeeze lemon over top and garnish with dill.'],
    goals: ['lose', 'fat_burn', 'build_muscle', 'maintain'],
    dietaryTags: ['gluten_free', 'paleo', 'keto'],
    tips: 'Salmon is excellent for recovery after workouts.',
  },
  {
    id: 'dn-002',
    name: 'Turkey Meatballs with Zucchini Noodles',
    description: 'Lean turkey meatballs over zoodles with marinara — low carb and satisfying.',
    mealType: 'dinner',
    calories: 340,
    protein: 30,
    carbs: 16,
    fat: 18,
    prepTime: '30 min',
    ingredients: ['300g ground turkey', '1 egg', '1/4 cup almond flour', '2 zucchinis (spiralized)', '1/2 cup marinara sauce', '1 tsp olive oil', 'Italian herbs', 'Salt'],
    steps: ['Mix turkey, egg, almond flour, herbs, and salt. Form into meatballs.', 'Bake at 400°F for 15 minutes.', 'Spiralize zucchinis into noodles.', 'Sauté zoodles in olive oil for 2 minutes.', 'Top with meatballs and warm marinara sauce.'],
    goals: ['lose', 'fat_burn', 'build_muscle'],
    dietaryTags: ['gluten_free', 'keto', 'paleo'],
  },
  {
    id: 'dn-003',
    name: 'Sweet Potato & Black Bean Chili',
    description: 'Warm, fiber-rich chili that is hearty and completely plant-based.',
    mealType: 'dinner',
    calories: 360,
    protein: 14,
    carbs: 58,
    fat: 8,
    prepTime: '40 min',
    ingredients: ['1 sweet potato (diced)', '1 can black beans', '1 can diced tomatoes', '1 onion (diced)', '2 garlic cloves', '1 tbsp chili powder', '1 tsp cumin', '2 cups vegetable broth'],
    steps: ['Sauté onion and garlic in a pot.', 'Add chili powder and cumin, stir for 30 seconds.', 'Add sweet potato, tomatoes, beans, and broth.', 'Simmer for 25 minutes until sweet potato is tender.', 'Season to taste and serve.'],
    goals: ['lose', 'maintain', 'gain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'Top with avocado for healthy fats.',
  },
  {
    id: 'dn-004',
    name: 'Shrimp Stir-Fry with Bell Peppers',
    description: 'Quick shrimp and veggie stir-fry with a savory garlic-ginger sauce.',
    mealType: 'dinner',
    calories: 290,
    protein: 28,
    carbs: 18,
    fat: 12,
    prepTime: '15 min',
    ingredients: ['200g shrimp (peeled)', '2 bell peppers (sliced)', '1 onion (sliced)', '2 garlic cloves', '1 tsp ginger (grated)', '2 tbsp soy sauce', '1 tsp sesame oil'],
    steps: ['Heat sesame oil in a wok over high heat.', 'Add garlic and ginger, stir for 20 seconds.', 'Add shrimp and cook 2 minutes per side.', 'Add bell peppers and onion, stir-fry 3 minutes.', 'Add soy sauce, toss, and serve.'],
    goals: ['lose', 'fat_burn', 'build_muscle', 'maintain'],
    dietaryTags: ['gluten_free', 'paleo', 'keto'],
  },
  {
    id: 'dn-005',
    name: 'Lemon Herb Roasted Chicken with Quinoa',
    description: 'Juicy roasted chicken thigh with fluffy quinoa and roasted carrots.',
    mealType: 'dinner',
    calories: 460,
    protein: 36,
    carbs: 42,
    fat: 16,
    prepTime: '40 min',
    ingredients: ['2 chicken thighs', '1 cup cooked quinoa', '2 carrots (chopped)', '1 lemon', '1 tbsp olive oil', 'Rosemary', 'Thyme', 'Salt and pepper'],
    steps: ['Preheat oven to 400°F.', 'Rub chicken with olive oil, lemon juice, herbs, salt, and pepper.', 'Place chicken and carrots on a baking sheet.', 'Roast for 30 minutes until chicken is 165°F.', 'Serve with quinoa and roasted carrots.'],
    goals: ['build_muscle', 'gain', 'maintain'],
    dietaryTags: ['gluten_free', 'paleo'],
  },

  // ===== PRE-WORKOUT =====
  {
    id: 'pre-001',
    name: 'Banana & Almond Butter Toast',
    description: 'Quick energy from banana and complex carbs for your training session.',
    mealType: 'pre_workout',
    calories: 240,
    protein: 6,
    carbs: 35,
    fat: 9,
    prepTime: '5 min',
    ingredients: ['1 slice whole wheat bread', '1 banana (sliced)', '1 tbsp almond butter'],
    steps: ['Toast the bread.', 'Spread almond butter evenly.', 'Top with banana slices.'],
    goals: ['lose', 'fat_burn', 'maintain', 'build_muscle', 'gain'],
    dietaryTags: ['vegetarian', 'vegan'],
    tips: 'Eat 30-45 minutes before your workout.',
  },
  {
    id: 'pre-002',
    name: 'Apple Slices with Peanut Butter',
    description: 'Simple pre-workout fuel with natural sugars and healthy fats.',
    mealType: 'pre_workout',
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 9,
    prepTime: '3 min',
    ingredients: ['1 apple (sliced)', '2 tbsp peanut butter'],
    steps: ['Slice the apple.', 'Serve with peanut butter for dipping.'],
    goals: ['lose', 'fat_burn', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'The natural sugars give you a quick energy kick.',
  },
  {
    id: 'pre-003',
    name: 'Oatmeal with Berries',
    description: 'Slow-release carbs from oats for sustained workout energy.',
    mealType: 'pre_workout',
    calories: 260,
    protein: 8,
    carbs: 45,
    fat: 6,
    prepTime: '10 min',
    ingredients: ['1/2 cup rolled oats', '1 cup water or milk', '1/4 cup mixed berries', '1 tsp honey'],
    steps: ['Cook oats with water or milk on stovetop.', 'Top with berries and honey.'],
    goals: ['build_muscle', 'gain', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
    tips: 'Eat 60-90 minutes before exercising for best results.',
  },
  {
    id: 'pre-004',
    name: 'Greek Yogurt with Honey & Walnuts',
    description: 'Balanced pre-workout snack with protein and fast-digesting carbs.',
    mealType: 'pre_workout',
    calories: 220,
    protein: 15,
    carbs: 22,
    fat: 8,
    prepTime: '3 min',
    ingredients: ['1 cup Greek yogurt', '1 tsp honey', '5 walnuts (chopped)'],
    steps: ['Spoon yogurt into a bowl.', 'Top with honey and walnuts.'],
    goals: ['lose', 'maintain', 'build_muscle'],
    dietaryTags: ['vegetarian', 'gluten_free'],
  },
  {
    id: 'pre-005',
    name: 'Date & Almond Energy Bites',
    description: 'No-bake bites packed with natural sugars for quick pre-workout fuel.',
    mealType: 'pre_workout',
    calories: 180,
    protein: 5,
    carbs: 28,
    fat: 7,
    prepTime: '10 min',
    ingredients: ['6 dates (pitted)', '1/4 cup almonds', '1 tbsp cocoa powder', '1 tbsp chia seeds', '1 tbsp water'],
    steps: ['Blend dates and almonds in a food processor.', 'Add cocoa powder, chia seeds, and water. Blend until sticky.', 'Roll into small balls.', 'Refrigerate for 15 minutes before eating.'],
    goals: ['lose', 'fat_burn', 'maintain', 'build_muscle', 'gain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'Make a batch and store in the fridge for the week.',
  },

  // ===== POST-WORKOUT =====
  {
    id: 'post-001',
    name: 'Chocolate Protein Smoothie',
    description: 'Fast-absorbing protein and carbs for muscle recovery.',
    mealType: 'post_workout',
    calories: 310,
    protein: 28,
    carbs: 38,
    fat: 7,
    prepTime: '5 min',
    ingredients: ['1 banana', '1 scoop chocolate protein powder', '1 cup almond milk', '1 tbsp peanut butter', '1/2 cup ice'],
    steps: ['Add all ingredients to a blender.', 'Blend until smooth.', 'Pour and enjoy immediately.'],
    goals: ['build_muscle', 'gain', 'maintain', 'lose', 'fat_burn'],
    dietaryTags: ['vegetarian', 'gluten_free'],
    tips: 'Consume within 30 minutes after your workout for best recovery.',
  },
  {
    id: 'post-002',
    name: 'Grilled Chicken Wrap',
    description: 'Lean protein wrapped with veggies for a satisfying post-workout meal.',
    mealType: 'post_workout',
    calories: 380,
    protein: 35,
    carbs: 32,
    fat: 12,
    prepTime: '15 min',
    ingredients: ['150g grilled chicken breast (sliced)', '1 whole wheat tortilla', '1/4 avocado', 'Lettuce', 'Tomato slices', '1 tbsp Greek yogurt'],
    steps: ['Lay out the tortilla.', 'Spread Greek yogurt as a base.', 'Layer chicken, avocado, lettuce, and tomato.', 'Roll tightly and slice in half.'],
    goals: ['build_muscle', 'gain', 'maintain', 'lose'],
    dietaryTags: ['vegetarian'],
  },
  {
    id: 'post-003',
    name: 'Tofu & Quinoa Power Bowl',
    description: 'Plant-based protein bowl for vegan athletes with recovery needs.',
    mealType: 'post_workout',
    calories: 420,
    protein: 24,
    carbs: 52,
    fat: 14,
    prepTime: '20 min',
    ingredients: ['150g firm tofu (cubed)', '1 cup cooked quinoa', '1 cup steamed broccoli', '2 tbsp soy sauce', '1 tsp sesame oil', '1 tsp olive oil', 'Sesame seeds'],
    steps: ['Pan-fry tofu in olive oil until golden on all sides.', 'Steam broccoli for 4 minutes.', 'Arrange quinoa, tofu, and broccoli in a bowl.', 'Drizzle with soy sauce and sesame oil.', 'Sprinkle with sesame seeds.'],
    goals: ['build_muscle', 'gain', 'maintain', 'lose'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
  },
  {
    id: 'post-004',
    name: 'Cottage Cheese & Fruit Bowl',
    description: 'Slow-digesting casein protein with fresh fruit for sustained recovery.',
    mealType: 'post_workout',
    calories: 260,
    protein: 20,
    carbs: 28,
    fat: 6,
    prepTime: '5 min',
    ingredients: ['1 cup cottage cheese', '1/2 cup strawberries', '1/2 banana (sliced)', '1 tbsp chia seeds'],
    steps: ['Spoon cottage cheese into a bowl.', 'Top with strawberries, banana, and chia seeds.'],
    goals: ['lose', 'fat_burn', 'maintain', 'build_muscle'],
    dietaryTags: ['vegetarian', 'gluten_free'],
    tips: 'Cottage cheese provides slow-release protein perfect for evening recovery.',
  },
  {
    id: 'post-005',
    name: 'Egg & Avocado Rice Bowl',
    description: 'Two fried eggs over rice with avocado — simple and protein-rich.',
    mealType: 'post_workout',
    calories: 400,
    protein: 18,
    carbs: 48,
    fat: 16,
    prepTime: '12 min',
    ingredients: ['2 eggs', '1 cup cooked brown rice', '1/2 avocado', '1 tsp olive oil', 'Soy sauce', 'Sesame seeds', 'Green onion'],
    steps: ['Cook rice if not already prepared.', 'Fry eggs in olive oil to your preference.', 'Serve rice in a bowl, top with eggs and sliced avocado.', 'Drizzle with soy sauce and sprinkle sesame seeds and green onion.'],
    goals: ['build_muscle', 'gain', 'maintain'],
    dietaryTags: ['vegetarian', 'gluten_free'],
  },

  // ===== SNACKS =====
  {
    id: 'sn-001',
    name: 'Trail Mix Energy Snack',
    description: 'Mix of nuts and dried fruit for a portable energy boost.',
    mealType: 'snack',
    calories: 200,
    protein: 6,
    carbs: 18,
    fat: 13,
    prepTime: '2 min',
    ingredients: ['2 tbsp almonds', '1 tbsp raisins', '1 tbsp dark chocolate chips', '1 tbsp pumpkin seeds'],
    steps: ['Mix all ingredients in a small container.', 'Store in an airtight container.'],
    goals: ['gain', 'build_muscle', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
  },
  {
    id: 'sn-002',
    name: 'Hummus & Veggie Plate',
    description: 'Fresh vegetables with creamy hummus for a light, fiber-rich snack.',
    mealType: 'snack',
    calories: 150,
    protein: 6,
    carbs: 18,
    fat: 7,
    prepTime: '5 min',
    ingredients: ['3 tbsp hummus', '1 cup cucumber sticks', '1 cup carrot sticks', '1 cup bell pepper strips'],
    steps: ['Arrange veggies on a plate.', 'Serve with hummus for dipping.'],
    goals: ['lose', 'fat_burn', 'maintain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
  },
  {
    id: 'sn-003',
    name: 'Dark Chocolate & Almonds',
    description: 'A small treat that satisfies cravings while providing healthy fats.',
    mealType: 'snack',
    calories: 170,
    protein: 4,
    carbs: 14,
    fat: 12,
    prepTime: '1 min',
    ingredients: ['2 squares dark chocolate (70%+)', '10 almonds'],
    steps: ['Serve dark chocolate with almonds.'],
    goals: ['lose', 'maintain', 'gain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free', 'paleo'],
    tips: 'Choose 70% or higher dark chocolate for antioxidants.',
  },
  {
    id: 'sn-004',
    name: 'Tuna & Celery Sticks',
    description: 'High-protein, ultra-low-carb snack for fat loss goals.',
    mealType: 'snack',
    calories: 120,
    protein: 16,
    carbs: 4,
    fat: 4,
    prepTime: '5 min',
    ingredients: ['1 can tuna (drained)', '3 celery stalks', '1 tsp Greek yogurt', 'Lemon juice', 'Salt and pepper'],
    steps: ['Mix tuna with yogurt, lemon juice, salt, and pepper.', 'Cut celery into sticks.', 'Spoon tuna onto celery sticks.'],
    goals: ['lose', 'fat_burn', 'build_muscle'],
    dietaryTags: ['gluten_free', 'keto', 'paleo'],
  },
  {
    id: 'sn-005',
    name: 'Berry Chia Pudding',
    description: 'Make-ahead pudding packed with omega-3s and antioxidants.',
    mealType: 'snack',
    calories: 180,
    protein: 5,
    carbs: 24,
    fat: 8,
    prepTime: '5 min + 2 hours chill',
    ingredients: ['3 tbsp chia seeds', '1 cup almond milk', '1 tbsp honey', '1/2 cup mixed berries'],
    steps: ['Whisk chia seeds, almond milk, and honey together.', 'Refrigerate for at least 2 hours until thick.', 'Top with berries before serving.'],
    goals: ['lose', 'maintain', 'gain'],
    dietaryTags: ['vegetarian', 'vegan', 'gluten_free'],
  },
];

export const MEAL_TYPE_LABELS: Record<string, string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  pre_workout: 'Pre-Workout',
  post_workout: 'Post-Workout',
  snack: 'Snack',
};

export const MEAL_TYPE_ICONS: Record<string, string> = {
  breakfast: '🌅',
  lunch: '☀️',
  dinner: '🌙',
  pre_workout: '⚡',
  post_workout: '💪',
  snack: '🍎',
};
